version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  web:
    build: .
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

volumes:
  redis_data:
