"""change habit_id from str to int for ability and motivatino schemas

Revision ID: 0fa4262d0bff
Revises: 83a0371575b0
Create Date: 2025-06-25 22:08:26.119231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa4262d0bff'
down_revision = '83a0371575b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###