"""ability can't do -> medium

Revision ID: 460fddeb317e
Revises: 0fa4262d0bff
Create Date: 2025-06-26 01:08:01.309783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460fddeb317e'
down_revision = '0fa4262d0bff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###