"""Add profile image URL to users table

Revision ID: 48966be3d548
Revises: f12a3058bea4
Create Date: 2025-06-23 17:37:57.879727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48966be3d548'
down_revision = 'f12a3058bea4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_motivations_id'), table_name='daily_motivations')
    op.drop_table('daily_motivations')
    op.alter_column('habits', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    op.alter_column('habits', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('daily_motivations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('habit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('motivation_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('daily_motivations_habit_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_motivations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_motivations_pkey'))
    )
    op.create_index(op.f('ix_daily_motivations_id'), 'daily_motivations', ['id'], unique=False)
    # ### end Alembic commands ###