"""fix_task_validations_cascade_delete

Revision ID: 613e44fb5b42
Revises: cab5f04f9559
Create Date: 2025-06-30 09:47:11.245618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613e44fb5b42'
down_revision = 'cab5f04f9559'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_validations_task_entry_id_fkey', 'task_validations', type_='foreignkey')
    op.create_foreign_key(None, 'task_validations', 'task_entries', ['task_entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_validations', type_='foreignkey')
    op.create_foreign_key('task_validations_task_entry_id_fkey', 'task_validations', 'task_entries', ['task_entry_id'], ['id'])
    # ### end Alembic commands ###