"""add cascade delete to onboarding_answers foreign key

Revision ID: 823ea6e92ac5
Revises: 38fc6fd1a04d
Create Date: 2025-06-22 18:21:13.119891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823ea6e92ac5'
down_revision = '38fc6fd1a04d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('onboarding_answers_user_id_fkey'), 'onboarding_answers', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboarding_answers', type_='foreignkey')
    op.create_foreign_key(op.f('onboarding_answers_user_id_fkey'), 'onboarding_answers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###