"""change habit_id in motivation/ability entries to integer

Revision ID: 83a0371575b0
Revises: 8f5114213162
Create Date: 2025-06-25 17:42:02.870513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a0371575b0'
down_revision = '8f5114213162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('level', sa.Enum('cant_do', 'hard', 'easy', name='abilitylevel'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_entries_id'), 'ability_entries', ['id'], unique=False)
    op.create_table('motivation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('level', sa.Enum('low', 'medium', 'high', name='motivationlevel'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivation_entries_id'), 'motivation_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motivation_entries_id'), table_name='motivation_entries')
    op.drop_table('motivation_entries')
    op.drop_index(op.f('ix_ability_entries_id'), table_name='ability_entries')
    op.drop_table('ability_entries')
    # ### end Alembic commands ###