"""add_friends_feature_with_user_profile_fields

Revision ID: 85a8b3141c0e
Revises: 613e44fb5b42
Create Date: 2025-06-30 21:01:41.220355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a8b3141c0e'
down_revision = '613e44fb5b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###