"""add_details_to_habits

Revision ID: 9c5cbc5bf022
Revises: c6e691e659f9
Create Date: 2025-06-22 21:57:29.166667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5cbc5bf022'
down_revision = 'c6e691e659f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('description', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('frequency', sa.String(), nullable=False))
    op.add_column('habits', sa.Column('validation_time', sa.String(), nullable=False))
    op.add_column('habits', sa.Column('difficulty', sa.String(), nullable=False))
    op.add_column('habits', sa.Column('proof_style', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'proof_style')
    op.drop_column('habits', 'difficulty')
    op.drop_column('habits', 'validation_time')
    op.drop_column('habits', 'frequency')
    op.drop_column('habits', 'description')
    # ### end Alembic commands ###