"""make onboarding habit_description not nullable

Revision ID: 9d009ee003f2
Revises: 9c5cbc5bf022
Create Date: 2025-06-22 23:47:19.474956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d009ee003f2'
down_revision = '9c5cbc5bf022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE onboarding_answers SET habit_description = '' WHERE habit_description IS NULL")
    op.alter_column('onboarding_answers', 'habit_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding_answers', 'habit_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###