"""Add cascade delete to habit foreign keys

Revision ID: c167d36297a9
Revises: c30ca152caae
Create Date: 2025-06-28 11:39:14.626479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c167d36297a9'
down_revision = 'c30ca152caae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ability_entries_habit_id_fkey', 'ability_entries', type_='foreignkey')
    op.create_foreign_key(None, 'ability_entries', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('motivation_entries_habit_id_fkey', 'motivation_entries', type_='foreignkey')
    op.create_foreign_key(None, 'motivation_entries', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_entries_habit_id_fkey', 'task_entries', type_='foreignkey')
    op.create_foreign_key(None, 'task_entries', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_entries', 'anchor_suggestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_entries', sa.Column('anchor_suggestion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_entries', type_='foreignkey')
    op.create_foreign_key('task_entries_habit_id_fkey', 'task_entries', 'habits', ['habit_id'], ['id'])
    op.drop_constraint(None, 'motivation_entries', type_='foreignkey')
    op.create_foreign_key('motivation_entries_habit_id_fkey', 'motivation_entries', 'habits', ['habit_id'], ['id'])
    op.drop_constraint(None, 'ability_entries', type_='foreignkey')
    op.create_foreign_key('ability_entries_habit_id_fkey', 'ability_entries', 'habits', ['habit_id'], ['id'])
    # ### end Alembic commands ###