"""remove_anchor_suggestion_from_task_entries

Revision ID: c30ca152caae
Revises: 5e1819758e86
Create Date: 2025-06-27 16:26:17.681964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30ca152caae'
down_revision = '5e1819758e86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###