"""add_friends_tables

Revision ID: faa4f448839c
Revises: 85a8b3141c0e
Create Date: 2025-06-30 21:02:24.509444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa4f448839c'
down_revision = '85a8b3141c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create friendships table
    op.create_table(
        'friendships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('friend_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'friend_id', name='unique_friendship')
    )
    op.create_index('idx_friendship_user_id', 'friendships', ['user_id'], unique=False)
    op.create_index('idx_friendship_friend_id', 'friendships', ['friend_id'], unique=False)
    op.create_index('idx_friendship_status', 'friendships', ['status'], unique=False)
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)

    # Create friend_requests table
    op.create_table(
        'friend_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('receiver_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='pending'),
        sa.Column('message', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sender_id', 'receiver_id', name='unique_friend_request')
    )
    op.create_index('idx_friend_request_sender_id', 'friend_requests', ['sender_id'], unique=False)
    op.create_index('idx_friend_request_receiver_id', 'friend_requests', ['receiver_id'], unique=False)
    op.create_index('idx_friend_request_status', 'friend_requests', ['status'], unique=False)
    op.create_index('idx_friend_request_created_at', 'friend_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_friend_requests_id'), 'friend_requests', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop friend_requests table
    op.drop_index(op.f('ix_friend_requests_id'), table_name='friend_requests')
    op.drop_index('idx_friend_request_created_at', table_name='friend_requests')
    op.drop_index('idx_friend_request_status', table_name='friend_requests')
    op.drop_index('idx_friend_request_receiver_id', table_name='friend_requests')
    op.drop_index('idx_friend_request_sender_id', table_name='friend_requests')
    op.drop_table('friend_requests')

    # Drop friendships table
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_index('idx_friendship_status', table_name='friendships')
    op.drop_index('idx_friendship_friend_id', table_name='friendships')
    op.drop_index('idx_friendship_user_id', table_name='friendships')
    op.drop_table('friendships')

    # ### end Alembic commands ###